services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: support_ticket
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
